FROM nginx:alpine
COPY . /usr/share/nginx/html
RUN echo 'server { listen 80; root /usr/share/nginx/html; index tattoo.html; location / { try_files $uri $uri/ /tattoo.html; } }' > /etc/nginx/conf.d/default.conf
EXPOSE 80
